using System.Reflection;

namespace Jalex.Repository.Utils
{
    public interface IReflectedTypeDescriptor
    {
        string TypeName { get; }
        bool IsIdAutoGenerated { get; }
        string IdPropertyName { get; }
        PropertyInfo[] Properties { get; }
    }
}
