using System;
using System.Diagnostics;
using Jalex.Infrastructure.Repository;

namespace Jalex.Authentication.Objects
{
    [DebuggerDisplay("User: {UserId} - Device: {DeviceId}")]
    public class AuthenticationToken
    {
        [Id(IsAutoGenerated = true)]
        public string Id { get; set; }

        [Indexed(Name = "UserAndDevice")]
        public string UserId { get; set; }

        [Indexed(Name = "UserAndDevice")]
        public string DeviceId { get; set; }

        public DateTime Created { get; set; }
    }
}
