using System;

namespace Jalex.Infrastructure.Repository
{
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
    public class IdAttribute : Attribute
    {
        public bool IsAutoGenerated { get; set; }

        public IdAttribute()
        {
            IsAutoGenerated = true;
        }
    }
}
